package com.javafirstproj;

public class Cricketer {
	static String board="BCCI"; 
	String Playername;
	int jerseyno;
	int age;
	int highestscore;
	public static void main(String[] args) {
		System.out.println("*******Player1********");
		Cricketer surya = new Cricketer();
		surya.Playername="Suryakumar Yadav(C)"; 
		surya.jerseyno=63;
		surya.age=35;
		surya.highestscore=117;
		System.out.println("Playername : " +surya.Playername);
		System.out.println("Jersey Number : "+surya.jerseyno);
		System.out.println("Age : "+surya.age);
		System.out.println("Highest Score : " +surya.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*******Player 2********");
		Cricketer abhi = new Cricketer();
		abhi.Playername="Abhishek Sharma"; 
		abhi.jerseyno=4;
		abhi.age=25;
		abhi.highestscore=135;
		System.out.println("Playername : " +abhi.Playername);
		System.out.println("Jersey Number : "+abhi.jerseyno);
		System.out.println("Age : "+abhi.age);
		System.out.println("Highest Score : " +abhi.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*************Player 3*************");
		Cricketer sanju = new Cricketer();
		sanju.Playername="Sanju Samson (WK)"; 
		sanju.jerseyno=9;
		sanju.age=31;
		sanju.highestscore=111;
		System.out.println("Playername : " +sanju.Playername);
		System.out.println("Jersey Number : "+sanju.jerseyno);
		System.out.println("Age : "+sanju.age);
		System.out.println("Highest Score : " +sanju.highestscore);
		System.out.println("Board : " + board);
		System.out.println("***********Player 4**************");
		Cricketer tilak = new Cricketer();
		tilak.Playername="Tilak Varma"; 
		tilak.jerseyno=72;
		tilak.age=23;
		tilak.highestscore=120;
		System.out.println("Playername : " +tilak.Playername);
		System.out.println("Jersey Number : "+tilak.jerseyno);
		System.out.println("Age : "+tilak.age);
		System.out.println("Highest Score : " +tilak.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*******Player 5********");
		Cricketer ishan = new Cricketer();
		ishan.Playername="Ishan Kishan"; 
		ishan.jerseyno=32;
		ishan.age=27;
		ishan.highestscore=89;
		System.out.println("Playername : " +ishan.Playername);
		System.out.println("Jersey Number : "+ishan.jerseyno);
		System.out.println("Age : "+ishan.age);
		System.out.println("Highest Score : " +ishan.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*******Player 6********");
		Cricketer rinku = new Cricketer();
		rinku.Playername="Rinku Singh"; 
		rinku.jerseyno=35;
		rinku.age=28;
		rinku.highestscore=69;
		System.out.println("Playername : " +rinku.Playername);
		System.out.println("Jersey Number : "+rinku.jerseyno);
		System.out.println("Age : "+rinku.age);
		System.out.println("Highest Score : " +rinku.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*******Player 7********");
		Cricketer hardik = new Cricketer();
		hardik.Playername="Abhishek Sharma"; 
		hardik.jerseyno=33;
		hardik.age=32;
		hardik.highestscore=71;
		System.out.println("Playername : " +hardik.Playername);
		System.out.println("Jersey Number : "+hardik.jerseyno);
		System.out.println("Age : "+hardik.age);
		System.out.println("Highest Score : " +hardik.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*******Player 8********");
		Cricketer shivam = new Cricketer();
		shivam.Playername="Shivam Dube"; 
		shivam.jerseyno=25;
		shivam.age=32;
		shivam.highestscore=65;
		System.out.println("Playername : " +shivam.Playername);
		System.out.println("Jersey Number : "+shivam.jerseyno);
		System.out.println("Age : "+shivam.age);
		System.out.println("Highest Score : " +shivam.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*******Player 9********");
		Cricketer jasprit = new Cricketer();
		jasprit.Playername="Jasprit Bumrah"; 
		jasprit.jerseyno=93;
		jasprit.age=32;
		jasprit.highestscore=14;
		System.out.println("Playername : " +jasprit.Playername);
		System.out.println("Jersey Number : "+jasprit.jerseyno);
		System.out.println("Age : "+jasprit.age);
		System.out.println("Highest Score : " +jasprit.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*******Player 10********");
		Cricketer singh = new Cricketer();
		singh.Playername="Arshdeep Singh"; 
		singh.jerseyno=2;
		singh.age=26;
		singh.highestscore=12;
		System.out.println("Playername : " +singh.Playername);
		System.out.println("Jersey Number : "+singh.jerseyno);
		System.out.println("Age : "+singh.age);
		System.out.println("Highest Score : " +singh.highestscore);
		System.out.println("Board : " + board);
		System.out.println("*******Player 11********");
		Cricketer  varun = new Cricketer();
		varun.Playername="Varun Chakravarthy"; 
		varun.jerseyno=29;
		varun.age=34;
		varun.highestscore=0;
		System.out.println("Playername : " +varun.Playername);
		System.out.println("Jersey Number : "+varun.jerseyno);
		System.out.println("Age : "+varun.age);
		System.out.println("Highest Score : " +varun.highestscore);
		System.out.println("Board : " + board);





	}

}
